[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sparc"
version = "2.0.0"
description = "Spectral Pattern Analysis for ROI Classification"
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.20.0",
    "matplotlib>=3.3.0",
    "scikit-learn>=1.0.0",
    "scipy>=1.7.0",
    "opencv-python>=4.5.0",
    "segment-anything>=1.0",
    "kneed>=0.7.0",
    "marslab",
    "rapid",
    "PyQt5",
    "PyYAML",
    "fs",
    "rich",
    "boto3",
    "gspread",
    "google-api-python-client",
    "sh==0.108",
    "scikit-image",
    "astropy",
    "pandas",
    "psutil"
]

[tool.setuptools.packages.find]
where = ["src"]